version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: splitwise_mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: splitwise
      MYSQL_USER: ayush
      MYSQL_PASSWORD: ayush123

    ports: 
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
